package proyectoed;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 * Interfaz grafica que modela la realidad de una calculadora 
 * @author Fernanda Leon, Mariana Aguayo, Marcio Tellez, Silvestre Rosales, Natalia Wilson
 */
public class GUI extends javax.swing.JFrame{
    private String entradaActual;
    private boolean resultadoCalculado = false;
    private String ultimoResultado = "";

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        sieteJButton = new javax.swing.JButton();
        unoJButton = new javax.swing.JButton();
        cuatroJButton = new javax.swing.JButton();
        ochoJButton = new javax.swing.JButton();
        dosJButton = new javax.swing.JButton();
        cincoJButton = new javax.swing.JButton();
        tresJButton = new javax.swing.JButton();
        nueveJButton = new javax.swing.JButton();
        seisJButton = new javax.swing.JButton();
        puntoJButton = new javax.swing.JButton();
        ceroJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        divJButton = new javax.swing.JButton();
        resta_JButton = new javax.swing.JButton();
        sumaJButton = new javax.swing.JButton();
        operadorJButton = new javax.swing.JButton();
        multiplicacionJButton = new javax.swing.JButton();
        dobleCeroJButton = new javax.swing.JButton();
        potenciaJButton = new javax.swing.JButton();
        izqParenJButton = new javax.swing.JButton();
        derParenJButton = new javax.swing.JButton();
        historialTextField = new javax.swing.JTextField();
        entradaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sieteJButton.setBackground(new java.awt.Color(255, 175, 204));
        sieteJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sieteJButton.setText("7");
        sieteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        unoJButton.setBackground(new java.awt.Color(255, 200, 221));
        unoJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unoJButton.setText("1");
        unoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        cuatroJButton.setBackground(new java.awt.Color(255, 175, 204));
        cuatroJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cuatroJButton.setText("4");
        cuatroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        ochoJButton.setBackground(new java.awt.Color(255, 175, 204));
        ochoJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ochoJButton.setText("8");
        ochoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        dosJButton.setBackground(new java.awt.Color(255, 175, 204));
        dosJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dosJButton.setText("2");
        dosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        cincoJButton.setBackground(new java.awt.Color(255, 175, 204));
        cincoJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cincoJButton.setText("5");
        cincoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        tresJButton.setBackground(new java.awt.Color(255, 175, 204));
        tresJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tresJButton.setText("3");
        tresJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        nueveJButton.setBackground(new java.awt.Color(255, 175, 204));
        nueveJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nueveJButton.setText("9");
        nueveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        seisJButton.setBackground(new java.awt.Color(255, 175, 204));
        seisJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seisJButton.setText("6");
        seisJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        puntoJButton.setBackground(new java.awt.Color(255, 200, 221));
        puntoJButton.setText(".");
        puntoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        ceroJButton.setBackground(new java.awt.Color(255, 175, 204));
        ceroJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ceroJButton.setText("0");
        ceroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        clearJButton.setBackground(new java.awt.Color(251, 111, 146));
        clearJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearJButton.setText("AC");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        divJButton.setBackground(new java.awt.Color(255, 200, 221));
        divJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divJButton.setText("/");
        divJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorJButtonActionPerformed(evt);
            }
        });

        resta_JButton.setBackground(new java.awt.Color(255, 200, 221));
        resta_JButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resta_JButton.setText("-");
        resta_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorJButtonActionPerformed(evt);
            }
        });

        sumaJButton.setBackground(new java.awt.Color(255, 200, 221));
        sumaJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumaJButton.setText("+");
        sumaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorJButtonActionPerformed(evt);
            }
        });

        operadorJButton.setBackground(new java.awt.Color(202, 233, 255));
        operadorJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        operadorJButton.setText("=");
        operadorJButton.setToolTipText("");
        operadorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualJButtonActionPerformed(evt);
            }
        });

        multiplicacionJButton.setBackground(new java.awt.Color(255, 200, 221));
        multiplicacionJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiplicacionJButton.setText("*");
        multiplicacionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorJButtonActionPerformed(evt);
            }
        });

        dobleCeroJButton.setBackground(new java.awt.Color(255, 200, 221));
        dobleCeroJButton.setText("00");
        dobleCeroJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        potenciaJButton.setBackground(new java.awt.Color(255, 200, 221));
        potenciaJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        potenciaJButton.setText("^");
        potenciaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorJButtonActionPerformed(evt);
            }
        });

        izqParenJButton.setBackground(new java.awt.Color(255, 200, 221));
        izqParenJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        izqParenJButton.setText("(");
        izqParenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        derParenJButton.setBackground(new java.awt.Color(255, 200, 221));
        derParenJButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        derParenJButton.setText(")");
        derParenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sieteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuatroJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unoJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobleCeroJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ochoJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cincoJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dosJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ceroJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nueveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seisJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tresJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puntoJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(izqParenJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sumaJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(multiplicacionJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(derParenJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resta_JButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(potenciaJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(operadorJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(divJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(historialTextField)
                    .addComponent(entradaTextField))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuatroJButton)
                            .addComponent(cincoJButton)
                            .addComponent(seisJButton))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sieteJButton)
                            .addComponent(ochoJButton)
                            .addComponent(nueveJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ceroJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puntoJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobleCeroJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dosJButton)
                                .addComponent(tresJButton)
                                .addComponent(unoJButton))
                            .addComponent(divJButton)
                            .addComponent(clearJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(operadorJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(multiplicacionJButton)
                                            .addComponent(potenciaJButton)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sumaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(resta_JButton))
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(derParenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(izqParenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Boton que deja en blanco ambos JTextPanes
     */
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        historialTextField.setText("");
        entradaTextField.setText("");
        resultadoCalculado = false;
        ultimoResultado = "";
    }//GEN-LAST:event_clearJButtonActionPerformed

    
    private void operadorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operadorJButtonActionPerformed
        String operador;
        
        if (entradaTextField.getText().contains("ERR")) {
            clearJButton.doClick();
        }
        operador = evt.getActionCommand();
        entradaActual = entradaTextField.getText();
        if (resultadoCalculado) {
            historialTextField.setText(ultimoResultado + operador);
            resultadoCalculado = false;
        } else {
            historialTextField.setText(historialTextField.getText() + entradaActual + operador);
        }
        entradaTextField.setText("");
    }//GEN-LAST:event_operadorJButtonActionPerformed

    private void numJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numJButtonActionPerformed
        String num;
        
        if (entradaTextField.getText().contains("ERR") || resultadoCalculado) {
            clearJButton.doClick();
        }
        num=evt.getActionCommand();
        entradaTextField.setText(entradaTextField.getText()+num);
    }//GEN-LAST:event_numJButtonActionPerformed
    
    /**
     * Boton que muestra el resultado de la operacion que escribio el usuario
     * En el cuadro de texto 'resultadoJPane'
     */
    private void igualJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualJButtonActionPerformed
        String resultado;
        String operacionCompleta;
        
        if (entradaTextField.getText().contains("ERR")) {
            clearJButton.doClick();
        }
        if (resultadoCalculado) {
            historialTextField.setText(entradaTextField.getText());
        }
        else {
            historialTextField.setText(historialTextField.getText() + entradaTextField.getText());
        }
        operacionCompleta = historialTextField.getText();
        try {
            resultado = "" + Calculadora.calcular(operacionCompleta);
        } catch (SintaxErr error) {
            resultado = "SINTAX ERR";
        }
        entradaTextField.setText(resultado);
        ultimoResultado = resultado;
        historialTextField.setText(operacionCompleta);
        resultadoCalculado = true;        
    }//GEN-LAST:event_igualJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ceroJButton;
    private javax.swing.JButton cincoJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JButton cuatroJButton;
    private javax.swing.JButton derParenJButton;
    private javax.swing.JButton divJButton;
    private javax.swing.JButton dobleCeroJButton;
    private javax.swing.JButton dosJButton;
    private javax.swing.JTextField entradaTextField;
    private javax.swing.JTextField historialTextField;
    private javax.swing.JButton izqParenJButton;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JButton multiplicacionJButton;
    private javax.swing.JButton nueveJButton;
    private javax.swing.JButton ochoJButton;
    private javax.swing.JButton operadorJButton;
    private javax.swing.JButton potenciaJButton;
    private javax.swing.JButton puntoJButton;
    private javax.swing.JButton resta_JButton;
    private javax.swing.JButton seisJButton;
    private javax.swing.JButton sieteJButton;
    private javax.swing.JButton sumaJButton;
    private javax.swing.JButton tresJButton;
    private javax.swing.JButton unoJButton;
    // End of variables declaration//GEN-END:variables
    
    
}
